version: '3.8'

services:
  bot:
    build: .
    container_name: howlongbot
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 